version: "3.9"

services:

  nginx:
    image: nginx:1.19-alpine
    container_name: iss-proxy
    restart: unless-stopped
    tty: true
    user: root
    depends_on:
      - core
    ports:
      - "80:80"
      - "443:443"
      - "5005:5005"
    volumes:
      - ./dist:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - iss-network

  webapp:
    image: kirilllapushinskiy/webapp:latest
    volumes:
      - ./dist/public:/app/dist
    env_file:
      - .env
    networks:
      - iss-network


  core:
    image: kirilllapushinskiy/iss-core-service:0.1.0
    container_name: iss-core-service
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./data:/data
      - ./config.yml:/project/config.yml
    networks:
      - iss-network
    command: >
      sh -c "alembic upgrade head && python3 -m app"

  postgres:
    image: postgres:15.1-alpine
    container_name: iss-database
    env_file:
      - .env
    command:
      - "postgres"
      - "-c"
      - "max_connections=10"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "work_mem=64MB"
      - "-c"
      - "maintenance_work_mem=128MB"
      - "-c"
      - "max_prepared_transactions=30"
      - "-c"
      - "random_page_cost=1.7"
      - "-c"
      - "temp_file_limit=1GB"
      - "-c"
      - "log_min_error_statement=INFO"
      - "-c"
      - "log_min_messages=FATAL"
      - "-c"
      - "log_statement=none"
      - "-c"
      - "log_destination=stderr"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d iss" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 7s
    restart: always
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - iss-network

networks:
  iss-network:
    driver: bridge
